### ISSUE TITLE
[BUG] kebab case fails with double extension

### ISSUE THREAD

**Issue by dacevedo12** [Igorkowalski94/eslint-plugin-project-structure#10]
Happens in 1.4.7 (latest at the time of writing)

**Describe the bug**
index.test.ts is not considered kebab-case (double extension)

**Expected behavior**
index.test.ts should be considered kebab-case
someFileName.test.ts should not considered kebab-case

**Additional context**
There are legit cases where files may have more than one extension. What do you think about making it work like name.split(".")[0]?

**Comment by dacevedo12** [comment]
Congratz on this tool BTW, it's very useful and fairly simple to use

**Comment by Igorkowalski94** [comment]
.test is not a file extension, it is part of the name. The extension in your case is "ts"

You can write it as follows:

```
{
   "name": "index.test",
   "extension": "ts"
}
```
or 
```
{
    "name": "/^${{kebab-case}}\\.test$/",
    "extension": "ts"
}
```

**Comment by Igorkowalski94** [comment]
Does this solve your problem and can I close the issue?

**Comment by dacevedo12** [comment]
ok, thanks
