### ISSUE TITLE
Make folder optional

### ISSUE THREAD

**Issue by Deadly0** [Igorkowalski94/eslint-plugin-project-structure#11]
**Is your feature request related to a problem? Please describe.**
I have project structure where some folders inside a module may not exists and it's ok. I can't describe such structure now

**Describe the solution you'd like**
Add a property to yaml/json setting on file/folder level (for example `optional: true|false`) when setled to true there is no error if folder not exists

**Additional context**
version 1.4.7

**Comment by Igorkowalski94** [comment]
By default, all files and folders are optional. Only existing files/folders are validated. If any of them do not meet the project structure conditions, an error is displayed. Unless I didn't understand something.

**Comment by Deadly0** [comment]
Sorry, it was my mistake. It works as expected
