### ISSUE TITLE
Feature request: Make file name match/contain the exported class name

### ISSUE THREAD

**Issue by DerZyklop** [Igorkowalski94/eslint-plugin-project-structure#12]
**Is your feature request related to a problem? Please describe.**
We usually have names like foo-bar.ts when it contains the code: `export class FooBar …`. This makes life easier because when you search for the class name in the file-search of your editor, the results always list the correct file.

Sometimes it happens that a file or class name gets renamed, but the dev forgets to rename the class or file accordingly, which could lead to a file called foo-bar.ts which contains `export class FooUtilities …`.

If you now pass the class name FooUtilities to your file-search it can’t find any match. 

**Describe the solution you'd like**
Perfect for my issue would be a ["Regex Parameter"](https://github.com/Igorkowalski94/eslint-plugin-project-structure?tab=readme-ov-file#regex-parameters) for the exported class name.

**Describe alternatives you've considered**
I tried [filenames/match-exported](https://www.npmjs.com/package/eslint-plugin-filenames), but it only catches exported functions and not exported files.
I tried [wc/file-name-matches-element](https://github.com/43081j/eslint-plugin-wc/blob/master/docs/rules/file-name-matches-element.md), but it does not seem to work when used in a non-web-component environment. 

**Additional context**
Not the same, but vue does something into this direction: https://eslint.vuejs.org/rules/match-component-file-name.html
Angular used to have some solution back in the pre-Angular2 days: https://github.com/EmmanuelDemey/eslint-plugin-angular/blob/master/docs/rules/file-name.md

**Comment by DerZyklop** [comment]
Not the same but vue does something into this direction https://eslint.vuejs.org/rules/match-component-file-name.html

**Comment by Igorkowalski94** [comment]
Sorry you waited so long, but I was working on version 2.0.0.
[project-structure/export-rules](https://github.com/Igorkowalski94/eslint-plugin-project-structure/blob/main/documentation/project-structure-export-rules.md) I think you will like it ;p 
also check [Migration guide to 2.0.0](https://github.com/Igorkowalski94/eslint-plugin-project-structure/blob/main/documentation/migration-to-2.0.0.md)

**Comment by Igorkowalski94** [comment]
After thinking about it for a while, I decided that there is no point in limiting myself only to export.

Using [project-structure/naming-rules](https://github.com/Igorkowalski94/eslint-plugin-project-structure/blob/main/documentation/project-structure-naming-rules.md) you will be able to validate whether your class has the name of the file in which it is located. As for file name validation, it will be validated by [project-structure/folder-structure](https://github.com/Igorkowalski94/eslint-plugin-project-structure/blob/main/documentation/project-structure-folder-structure.md).

Let me know if it meets your expectations or if you have any problems/questions.

Also check: [Migration guide to 2.0.0](https://github.com/Igorkowalski94/eslint-plugin-project-structure/blob/main/documentation/migration-to-2.0.0.md)

**Comment by Igorkowalski94** [comment]
Small update: I added the option to add rules only for exported name types.  
https://github.com/Igorkowalski94/eslint-plugin-project-structure/blob/main/documentation/project-structure-naming-rules.md#allow-names-export
