### ISSUE TITLE
[Feature request] {parentName} regex parameter as kebab case

### ISSUE THREAD

**Issue by rishitank** [Igorkowalski94/eslint-plugin-project-structure#14]
**Is your feature request related to a problem? Please describe.**
I would like to know if there is a way to get the `{parentName}` in kebab case? Currently as far as I know it is only available as camelCase and PascalCase.

**Describe the solution you'd like**
I would like to validate that the file within a folder matches the folder name, which would be in kebab case using the folder structure rules.

**Describe alternatives you've considered**
For now I have only uses `use-{kebab-case}.jsx` as a file name, but this would mean there is potential for it to deviate from the folder name.

**Additional context**

**Comment by Igorkowalski94** [comment]
Version 2.3.0 has been released

**Comment by rishitank** [comment]
Thank you!
