### ISSUE TITLE
[Feature request] Support for jest.mocks with independent modules

### ISSUE THREAD

**Issue by rishitank** [Igorkowalski94/eslint-plugin-project-structure#15]
**Is your feature request related to a problem? Please describe.**
When defining import rules using independent modules, currently this doesn't apply to `jest.mock` and `jest.requireActual` imports in test files.

**Describe the solution you'd like**
I would like the same import rules that define who can import who, but with `jest.mock` and `jest.requireActual` imports too.

**Describe alternatives you've considered**
Currently it is a manual process to check import statements in test files.

**Additional context**

**Comment by Igorkowalski94** [comment]
Please move this feature request [here](https://github.com/Igorkowalski94/eslint-plugin-project-structure/discussions/new?category=ideas). I want the issues section to be reserved only for bugs and documentation errors.
