### ISSUE TITLE
[BUG][File Composition] Can't mix type and variable selectors with same name

### ISSUE THREAD

**Issue by FredericEspiau** [Igorkowalski94/eslint-plugin-project-structure#20]
**Describe the bug**

If a `type` selector and a `variableExpression` selector have the same format, then the rules will clash

<img width="1229" alt="Screenshot 2024-10-09 at 13 07 07" src="https://github.com/user-attachments/assets/45498c6f-e01d-41b7-a682-4d6068b5342a">
<img width="450" alt="Screenshot 2024-10-09 at 13 07 31" src="https://github.com/user-attachments/assets/bbf4dc0a-b1df-4023-b795-c478b4ecd97a">

**Expected behavior**

To be able to have both an `Id` type and an `Id` variable.

**Additional context**

Thanks for the hard work

**Comment by Igorkowalski94** [comment]
Currently, the logic is based on the name of a given selector without taking its type into account. I'll think about whether there's a way to work around this. As a temporary solution, you can either skip `positionIndex` for one of them or change the name of the type to `IdType`.

**Comment by Igorkowalski94** [comment]
Fixed in [v3.5.0](https://github.com/Igorkowalski94/eslint-plugin-project-structure/releases/tag/v3.5.0)
