### ISSUE TITLE
[BUG] IndependentModules - allowImport 

### ISSUE THREAD

**Issue by Waxoussou** [Igorkowalski94/eslint-plugin-project-structure#24]
"eslint-plugin-project-structure": "^3.10.1",

**Describe the bug**
AllowImportsFrom  working not well with external dependencies. (vue/lodash). 

project Structure :
```
ProjectRoot
  |- commons
        |- utils
        |- types
        |- ...
  |- commons.light
  |- rootApp
  |- SubApp 
```
IndependatModule config (in jsonc)
```json

{
            "name": "utils",
            "pattern": "commons/**",
            "allowExternalImports": false,
            "allowImportsFrom": [
                "lodash"
            ],
            "errorMessage": "🔥 Only the `commons` folder can importitems from lodash. 🔥"
        }
```

Expected Behavior : 
Lodash should no be allowed to be imported from anywhere except from files in commons folder.

Result : 
In common/utils folder 
 `import  omit from "lodash.omit";` raise an error
 I've tried to change the lodash importFrom rule to `lodash**`, `lodash.**`. Same result. 
 Also by removing `allowExternalImport:false` and using negative allowImport like `!lodash`
And lastly I  tried to do the same with vue dependency but result is the same.

**Comment by Igorkowalski94** [comment]
Hi @Waxoussou,
 
Try it this way

```js
{
            "name": "utils",
            "pattern": "commons/**",
            "allowExternalImports": false,
            "allowImportsFrom": [
                "lodash/*"
            ],
            "errorMessage": "🔥 Only the `commons` folder can importitems from lodash. 🔥"
}
```
If it doesn’t help, enable debugMode and please show me what the error looks like.
```js
{ "debugMode": true }
```

**Comment by Igorkowalski94** [comment]
Also, update the version to ^3.10.4. In the meantime, there have been important fixes to independent-modules.

**Comment by Igorkowalski94** [comment]
In version 2.10.5, I added support for external imports that use `.` instead of `/` or `:`. Could you check if it works correctly with this configuration?

```js
{
            "name": "utils",
            "pattern": "commons/**",
            "allowExternalImports": false,
            "allowImportsFrom": [
                "lodash/**",
                "lodash.*"
            ],
            "errorMessage": "🔥 Only the `commons` folder can importitems from lodash. 🔥"
}
```

**Comment by Waxoussou** [comment]
Hello @Igorkowalski94 ,

I have updated to v.3.10.4
and update the `independentModule.jsonc` as you advise me too (with `lodash/**` & `lodash.*`) but unfortunately, this does not fix my issue. 
Changing from lodash. to lodash/ seems to correct the issue. 
But what I don't understand is why the issue seems to appear as well with `vue` import (since there is no issue with the path in that case). 
setting the debugMode On give me the following result : 
 ```jsonc
 //independentModule.jsonc
 modules": [
        {
            "name": "utils",
            "pattern": "commons/**",
            "allowExternalImports": false,
            "allowImportsFrom": [
                "commons/**",
                "vue",
                "lodash/**", // import x from "lodash/omit", import x from "lodash"
                "lodash.*" // import x from "lodash.omit"
            ],
            "errorMessage": "🔥 `commons` folder can importitems from ... . 🔥"
        }
```
 result for : `import omit from "lodash.omit";`     
```eslint
🔥 `commons` folder can importitems from ... . 🔥

File path   = "commons/utils/object/omit.ts"
Import path = "lodash.omit/index.d.ts"
{family}    = "NO_FAMILY"
{dirname}   = "commons/utils/object"

allowImportsFrom:
"commons/**"
"vue"
"lodash/**"
"lodash.*"
``` 

with `import {computed} from 'vue';`
```eslint 
🔥 `commons` folder can importitems from ... . 🔥

File path   = "commons/utils/object/omit.ts"
Import path = "vue/index.mjs"
{family}    = "NO_FAMILY"
{dirname}   = "commons/utils/object"

allowImportsFrom:
"commons/**"
"vue"
"lodash/**"
"lodash.*"
```

**Comment by Igorkowalski94** [comment]
Do an update to version 2.10.5 and try it like that:
```js
{
  "allowImportsFrom": [
      "lodash/**", 
      "lodash.*/**",  
       "vue/**"
  ],
}
```

**Comment by Waxoussou** [comment]
Sorry haven't got time to try out your last comment yet. 
I'll come back to you as soon as I can

**Comment by Waxoussou** [comment]
Hi @Igorkowalski94 ,
I've updated my code and the version as you said, and it seems to work as expected now. 
Thanks a lot for your time and work !
