### ISSUE TITLE
[BUG] Folder names with brackets causing problems.

### ISSUE THREAD

**Issue by cccaaannn** [Igorkowalski94/eslint-plugin-project-structure#27]
**Describe the bug**

I am getting error with this path
src/app/learn-more/(components)

It works when I change the path to this
src/app/learn-more/components

**Additional context**
Version: 3.10.9

Config
```
{
	name: "App",
	allowExternalImports: true,
	pattern: "src/app/**",
	errorMessage: "Not allowed",
	allowImportsFrom: [
		"{family}/**"
	]
}
```

Debug message
```
File path   = "src/app/learn-more/(components)/card.tsx"
Import path = "src/app/learn-more/(components)/card-definitions.ts"
{family}    = "src/app/learn-more/(components)"
{dirname}   = "src/app/learn-more/(components)"

allowImportsFrom:
"src/app/learn-more/(components)/**"
```

**Comment by Igorkowalski94** [comment]
The library uses [micromatch](https://github.com/micromatch/micromatch?tab=readme-ov-file#matching-features) for patterns. In [micromatch](https://github.com/micromatch/micromatch?tab=readme-ov-file#matching-features), parentheses are special characters, so you need to define them this way.


```mjs
{
	name: "App",
	allowExternalImports: true, // <= You can remove the default.
	pattern: "src/app/**",
	errorMessage: "Not allowed",
	allowImportsFrom: [
		"{family}/**",
		"{family}/**/\\(components\\)/**"
	]
}
```

**Comment by Igorkowalski94** [comment]
Hmm, but then you won’t be able to use {family}... In that case, I need to think it over.

**Comment by cccaaannn** [comment]
I can use them without brackets for this project but this will probably be problem for Nextjs users, I really don't like their weird folder syntax 🤷🏻‍♂️.

**Comment by Igorkowalski94** [comment]
Done, [v3.10.11](https://github.com/Igorkowalski94/eslint-plugin-project-structure/releases/tag/v3.10.11)

**Comment by Igorkowalski94** [comment]
@cccaaannn  If everything works fine, please let me know and close this issue.

**Comment by cccaaannn** [comment]
Thanks it is working now. 😃

**Comment by Igorkowalski94** [comment]
Hi, @cccaaannn, [v3.11.0](https://github.com/Igorkowalski94/eslint-plugin-project-structure/releases/tag/v3.11.0)

also support for app/[slug], app/[[...slug]], app/.someName, app/{hello}, app/hello!... etc.
