### ISSUE TITLE
Configurable PROJECT_STRUCTURE_CACHE_FILE_NAME

### ISSUE THREAD

**Issue by ruchevits** [Igorkowalski94/eslint-plugin-project-structure#28]
Hey there!

Firstly, thank you for the great package, it perfectly integrates into our linting setup!

Would you consider allowing configurable cache file location?

It's a non-breaking change and I would be happy to make a PR.

**Comment by Igorkowalski94** [comment]
Hi @ruchevits , this option is now available. You can use [projectRoot](https://github.com/Igorkowalski94/eslint-plugin-project-structure/wiki/project%E2%80%91structure-%E2%80%8Bfolder%E2%80%91structure#project-root).

**Comment by Igorkowalski94** [comment]
@ruchevits  If the answer is sufficient, please let me know and close the issue.

**Comment by Igorkowalski94** [comment]
@ruchevits In version [3.13.0](https://github.com/Igorkowalski94/eslint-plugin-project-structure/releases/tag/v3.13.0), I added the option to change the location of the `projectStructure.cache.json` file generation for greater flexibility.
