### ISSUE TITLE
YAML config isn't being read properly

### ISSUE THREAD

**Issue by jessezhang91** [Igorkowalski94/eslint-plugin-project-structure#3]
Hello, first off thanks for this plugin!

I noticed when trying to configure a YML projectStructurerc file that it isn't being loaded. Looking at the code, I think the problem is here:
https://github.com/Igorkowalski94/eslint-plugin-project-structure/blob/main/src/validators/validateFileStructure/helpers/readConfigFile.ts#L12-L22

The YAML loader is falling through to the JSON loader on success rather than returning.

It should instead probably be something like:
```
    let config = null;

    try {
        return load(readFileSync(configPath, "utf8"));
    } catch (error) {
    }

    return JSON.parse(readFileSync(configPath, "utf-8"));
```

**Comment by Igorkowalski94** [comment]
Fixed in version 1.4.0. Thank you for using my plugin and reporting a bug ;*
