### ISSUE TITLE
Simple rule for components/AbcXyz not working

### ISSUE THREAD

**Issue by tamhv** [Igorkowalski94/eslint-plugin-project-structure#9]
**Describe the bug**
I'm testing a simple structure
```
#ls -la
. 
app
public
components
- AbcXyz
   - Aaa
     - aa.tsx
   - Abc.tsx   

```

But i keep getting the eslint error at AbcXyz

![Screenshot 2023-08-30 at 09 40 03](https://github.com/Igorkowalski94/eslint-plugin-project-structure/assets/5440638/8f399220-eecf-4648-964b-a0d23fae96e1)

![Screenshot 2023-08-30 at 09 40 12](https://github.com/Igorkowalski94/eslint-plugin-project-structure/assets/5440638/b4041cd7-ab46-4491-b3fe-96d3ddbc6980)
![Screenshot 2023-08-30 at 09 40 22](https://github.com/Igorkowalski94/eslint-plugin-project-structure/assets/5440638/24a39ccd-aa84-4bf2-b322-6151802ad476)

**To Reproduce**

**Expected behavior**
AbcXyz should be correct structure

**Add your projectStructure file**
```json
{
  "$schema": "node_modules/eslint-plugin-project-structure/projectStructure.schema.json",
  "structure": {
    "children": [
      {
        "name": "public",
        "children": []
      },
      {
        "name": "app",
        "children": [
          {
            "name": "globals",
            "extension": "css"
          },
          {
            "name": "/^(layout|page)$/",
            "extension": "tsx"
          },
          {
            "name": "favicon",
            "extension": "ico"
          }
        ]
      },
      {
        "name": "components",
        "children": [
          {
            "ruleId": "component_folder"
          }
        ]
      },
      {
        "extension": "*"
      }
    ]
  },
  "rules": {
    "component_folder": {
      "name": "/^${{PascalCase}}$/"
    }
  }
}

```

** Operating system, Node.js an npm versions, and eslint version (please complete the following information):**

-   OS: macOS
-   Node.js: v18.17.1
-   npm: 9.6.7
-   ESLint:  eslint@8.46.0

**Additional context**

**Comment by Igorkowalski94** [comment]
Everything works fine for me locally. 

I see that the error is not from the console but from the file. Have you tried closing and opening the file? 
Sometimes when changing the structure, eslint may show the previous state. 

Please show me the whole structure including root like this:
![image](https://github.com/Igorkowalski94/eslint-plugin-project-structure/assets/49439801/bb9424ae-8647-48a9-90ca-195e31dd1881)

**Comment by Igorkowalski94** [comment]
I was able to reproduce your problem on 1.4.3. You are using the configuration from 1.4.4 which adds support for validating multiple structure folders/files. Upgrade your version to the latest. https://github.com/Igorkowalski94/eslint-plugin-project-structure/releases/tag/v1.4.4
